<?php

declare(strict_types=1);

namespace Modules\Foundation\Infrastructure\Persistence;

/** Database identity and reference metadata. Every record is stored under its numeric id. */
final class RecordSchema
{
    public const IDENTITY_NAMES = [
        'area_hierarchies' => 'area_hierarchy_id',
        'areas' => 'area_id',
        'audit_events' => 'audit_id',
        'authentication_credentials' => 'credential_id',
        'cities' => 'city_id',
        'commitment_schedule_scopes' => 'commitment_schedule_scope_id',
        'commitment_schedule_versions' => 'commitment_schedule_version_id',
        'commitment_schedule_windows' => 'commitment_schedule_window_id',
        'commitment_schedules' => 'commitment_schedule_id',
        'consignment_number_allocations' => 'allocation_id',
        'consignment_number_ranges' => 'range_id',
        'consignment_pricing_charge_lines' => 'pricing_charge_line_id',
        'consignment_pricing_versions' => 'pricing_version_id',
        'consignment_status_events' => 'status_event_id',
        'consignments' => 'consignment_id',
        'countries' => 'country_id',
        'coverage_policies' => 'coverage_policy_id',
        'coverage_policy_versions' => 'coverage_policy_version_id',
        'coverage_rules' => 'coverage_rule_id',
        'crm_activities' => 'activity_id',
        'crm_activity_participants' => 'activity_participant_id',
        'crm_bank_accounts' => 'bank_account_id',
        'crm_catalog_categories' => 'catalog_category_id',
        'crm_catalog_channels' => 'catalog_channel_id',
        'crm_catalog_item_industry' => 'catalog_item_industry_id',
        'crm_catalog_items' => 'catalog_item_id',
        'crm_catalog_personas' => 'catalog_persona_id',
        'crm_catalog_sales_models' => 'catalog_sales_model_id',
        'crm_contact_points' => 'contact_point_id',
        'crm_contracts' => 'contract_id',
        'crm_customer_address' => 'customer_address_id',
        'crm_customer_departments' => 'customer_department_id',
        'crm_customer_extended_details' => 'customer_extended_detail_id',
        'crm_customer_financial_details' => 'customer_financial_detail_id',
        'crm_customer_industry' => 'customer_industry_id',
        'crm_customers' => 'customer_id',
        'crm_deliveries' => 'delivery_id',
        'crm_external_invoices' => 'external_invoice_id',
        'crm_financial_allocations' => 'financial_allocation_id',
        'crm_financial_entries' => 'financial_entry_id',
        'crm_industries' => 'industry_id',
        'crm_membership_events' => 'membership_event_id',
        'crm_notification_inbox' => 'notification_inbox_id',
        'crm_opportunities' => 'opportunity_id',
        'crm_opportunity_events' => 'opportunity_event_id',
        'crm_positions' => 'position_id',
        'crm_relationships' => 'relationship_id',
        'crm_sales_document_versions' => 'sales_document_version_id',
        'crm_sales_documents' => 'sales_document_id',
        'crm_sales_funnel' => 'sales_funnel_id',
        'crm_sales_funnel_steps' => 'sales_funnel_step_id',
        'crm_task_assignment_events' => 'task_assignment_event_id',
        'crm_tasks' => 'task_id',
        'crm_team_members' => 'team_member_id',
        'crm_teams' => 'team_id',
        'delivery_task_history' => 'delivery_task_history_id',
        'delivery_tasks' => 'delivery_task_id',
        'document_categories' => 'document_category_id',
        'document_links' => 'document_link_id',
        'documents' => 'document_id',
        'driver_capabilities' => 'driver_capability_id',
        'drivers' => 'driver_id',
        'hq_tenants' => 'hq_id',
        'idempotency_records' => 'record_id',
        'last_mile_resolution_evidence' => 'last_mile_resolution_id',
        'manifest_parcels' => 'manifest_parcel_id',
        'manifests' => 'manifest_id',
        'nodes' => 'node_id',
        'notification_deliveries' => 'delivery_id',
        'operational_exception_cases' => 'exception_case_id',
        'operational_exception_history' => 'exception_history_id',
        'operational_status_revisions' => 'revision_id',
        'operational_statuses' => 'status_id',
        'otp_challenges' => 'challenge_id',
        'outbox_events' => 'event_id',
        'parcel_custody_events' => 'custody_event_id',
        'parcels' => 'parcel_id',
        'permissions' => 'permission_id',
        'pickup_tasks' => 'pickup_task_id',
        'pricing_charge_lines' => 'charge_line_id',
        'pricing_charge_types' => 'charge_type_id',
        'pricing_quote_lines' => 'quote_line_id',
        'pricing_quotes' => 'quote_id',
        'pricing_snapshots' => 'pricing_snapshot_id',
        'pricing_zone_members' => 'zone_member_id',
        'pricing_zone_set_versions' => 'zone_set_version_id',
        'pricing_zone_sets' => 'pricing_zone_set_id',
        'pricing_zones' => 'pricing_zone_id',
        'provinces' => 'province_id',
        'role_permissions' => 'role_permission_id',
        'roles' => 'role_id',
        'route_definition_legs' => 'route_definition_leg_id',
        'route_definition_version_legs' => 'route_definition_version_leg_id',
        'route_definition_versions' => 'route_definition_version_id',
        'route_definitions' => 'route_definition_id',
        'route_plan_legs' => 'route_plan_leg_id',
        'route_plan_resolution_evidence' => 'resolution_evidence_id',
        'route_plans' => 'route_plan_id',
        'service_availability_bindings' => 'availability_binding_id',
        'service_coverage_references' => 'coverage_reference_id',
        'service_eligibility_rules' => 'eligibility_rule_id',
        'service_legacy_mappings' => 'legacy_mapping_id',
        'service_offering_commitment_bindings' => 'offering_commitment_binding_id',
        'service_offering_option_rules' => 'offering_option_rule_id',
        'service_offering_versions' => 'service_offering_version_id',
        'service_offerings' => 'service_offering_id',
        'service_option_versions' => 'service_option_version_id',
        'service_options' => 'service_option_id',
        'service_type_versions' => 'service_type_version_id',
        'service_types' => 'service_type_id',
        'shipping_method_versions' => 'shipping_method_version_id',
        'shipping_methods' => 'shipping_method_id',
        'tariff_families' => 'tariff_family_id',
        'tariff_rate_rules' => 'rate_rule_id',
        'tariff_versions' => 'tariff_version_id',
        'tenant_module_entitlements' => 'entitlement_id',
        'user_invitations' => 'invitation_id',
        'user_role_assignments' => 'assignment_id',
        'user_sessions' => 'session_id',
        'users' => 'user_id',
        'vehicles' => 'vehicle_id',
    ];

    public const REFERENCES = [
        'crm_customers' => [
            'hq_id' => ['hq_tenants', 'id'],
            'assignee_id' => ['users', 'id'],
            'created_by' => ['users', 'id'],
        ],
        'crm_customer_address' => [
            'hq_id' => ['hq_tenants', 'id'],
            'customer_id' => ['crm_customers', 'id'],
            'province_id' => ['provinces', 'id'],
            'city_id' => ['cities', 'id'],
            'created_by' => ['users', 'id'],
        ],
        'crm_customer_extended_details' => [
            'hq_id' => ['hq_tenants', 'id'],
            'customer_id' => ['crm_customers', 'id'],
            'evaluated_by' => ['users', 'id'],
            'created_by' => ['users', 'id'],
        ],
        'crm_customer_financial_details' => [
            'hq_id' => ['hq_tenants', 'id'],
            'customer_id' => ['crm_customers', 'id'],
            'created_by' => ['users', 'id'],
        ],
        'crm_bank_accounts' => [
            'hq_id' => ['hq_tenants', 'id'],
            'customer_id' => ['crm_customers', 'id'],
            'created_by' => ['users', 'id'],
        ],
        'crm_external_invoices' => [
            'hq_id' => ['hq_tenants', 'id'],
            'customer_id' => ['crm_customers', 'id'],
            'contract_id' => ['crm_contracts', 'id'],
            'opportunity_id' => ['crm_opportunities', 'id'],
            'created_by' => ['users', 'id'],
        ],
        'crm_financial_entries' => [
            'hq_id' => ['hq_tenants', 'id'],
            'customer_id' => ['crm_customers', 'id'],
            'invoice_id' => ['crm_external_invoices', 'id'],
            'reverses_id' => ['crm_financial_entries', 'id'],
            'created_by' => ['users', 'id'],
        ],
        'crm_financial_allocations' => [
            'hq_id' => ['hq_tenants', 'id'],
            'receipt_entry_id' => ['crm_financial_entries', 'id'],
            'invoice_id' => ['crm_external_invoices', 'id'],
            'created_by' => ['users', 'id'],
        ],
        'crm_contact_points' => [
            'hq_id' => ['hq_tenants', 'id'],
            'customer_id' => ['crm_customers', 'id'],
            'relationship_id' => ['crm_relationships', 'id'],
            'address_id' => ['crm_customer_address', 'id'],
            'created_by' => ['users', 'id'],
        ],
        'crm_relationships' => [
            'hq_id' => ['hq_tenants', 'id'],
            'person_customer_id' => ['crm_customers', 'id'],
            'company_customer_id' => ['crm_customers', 'id'],
            'position_id' => ['crm_positions', 'id'],
            'created_by' => ['users', 'id'],
        ],
        'crm_contracts' => [
            'hq_id' => ['hq_tenants', 'id'],
            'customer_id' => ['crm_customers', 'id'],
            'opportunity_id' => ['crm_opportunities', 'id'],
            'proforma_version_id' => ['crm_sales_document_versions', 'id'],
            'created_by' => ['users', 'id'],
        ],
        'crm_catalog_items' => [
            'hq_id' => ['hq_tenants', 'id'],
            'category_id' => ['crm_catalog_categories', 'id'],
            'buyer_persona_id' => ['crm_catalog_personas', 'id'],
            'sales_model_id' => ['crm_catalog_sales_models', 'id'],
            'created_by' => ['users', 'id'],
        ],
        'crm_catalog_categories' => [
            'hq_id' => ['hq_tenants', 'id'],
            'parent_id' => ['crm_catalog_categories', 'id'],
            'created_by' => ['users', 'id'],
        ],
        'crm_catalog_personas' => [
            'hq_id' => ['hq_tenants', 'id'],
            'created_by' => ['users', 'id'],
        ],
        'crm_catalog_sales_models' => [
            'hq_id' => ['hq_tenants', 'id'],
            'created_by' => ['users', 'id'],
        ],
        'crm_catalog_item_industry' => [
            'hq_id' => ['hq_tenants', 'id'],
            'catalog_item_id' => ['crm_catalog_items', 'id'],
            'industry_id' => ['crm_industries', 'id'],
            'created_by' => ['users', 'id'],
        ],
        'crm_customer_industry' => [
            'hq_id' => ['hq_tenants', 'id'],
            'customer_id' => ['crm_customers', 'id'],
            'industry_id' => ['crm_industries', 'id'],
            'created_by' => ['users', 'id'],
        ],
        'crm_industries' => [
            'hq_id' => ['hq_tenants', 'id'],
            'created_by' => ['users', 'id'],
        ],
        'crm_sales_documents' => [
            'hq_id' => ['hq_tenants', 'id'],
            'customer_id' => ['crm_customers', 'id'],
            'opportunity_id' => ['crm_opportunities', 'id'],
            'current_version_id' => ['crm_sales_document_versions', 'id'],
            'created_by' => ['users', 'id'],
        ],
        'crm_sales_document_versions' => [
            'hq_id' => ['hq_tenants', 'id'],
            'document_id' => ['crm_sales_documents', 'id'],
            'previous_version_id' => ['crm_sales_document_versions', 'id'],
            'created_by' => ['users', 'id'],
        ],
        'crm_tasks' => [
            'hq_id' => ['hq_tenants', 'id'],
            'customer_id' => ['crm_customers', 'id'],
            'opportunity_id' => ['crm_opportunities', 'id'],
            'assignee_id' => ['users', 'id'],
            'created_by' => ['users', 'id'],
        ],
        'crm_opportunities' => [
            'hq_id' => ['hq_tenants', 'id'],
            'customer_id' => ['crm_customers', 'id'],
            'funnel_id' => ['crm_sales_funnel', 'id'],
            'current_step_id' => ['crm_sales_funnel_steps', 'id'],
            'assignee_id' => ['users', 'id'],
            'created_by' => ['users', 'id'],
        ],
        'crm_sales_funnel_steps' => [
            'hq_id' => ['hq_tenants', 'id'],
            'funnel_id' => ['crm_sales_funnel', 'id'],
            'created_by' => ['users', 'id'],
        ],
        'crm_sales_funnel' => [
            'hq_id' => ['hq_tenants', 'id'],
            'catalog_item_id' => ['crm_catalog_items', 'id'],
            'created_by' => ['users', 'id'],
        ],
        'crm_opportunity_events' => [
            'hq_id' => ['hq_tenants', 'id'],
            'opportunity_id' => ['crm_opportunities', 'id'],
            'actor_id' => ['users', 'id'],
            'evidence_activity_id' => ['crm_activities', 'id'],
            'from_funnel_id' => ['crm_sales_funnel', 'id'],
            'from_step_id' => ['crm_sales_funnel_steps', 'id'],
            'to_funnel_id' => ['crm_sales_funnel', 'id'],
            'to_step_id' => ['crm_sales_funnel_steps', 'id'],
            'created_by' => ['users', 'id'],
        ],
        'document_categories' => [
            'hq_id' => ['hq_tenants', 'id'],
            'parent_id' => ['document_categories', 'id'],
            'created_by' => ['users', 'id'],
        ],
        'documents' => [
            'hq_id' => ['hq_tenants', 'id'],
            'category_id' => ['document_categories', 'id'],
            'created_by' => ['users', 'id'],
        ],
        'document_links' => [
            'hq_id' => ['hq_tenants', 'id'],
            'document_id' => ['documents', 'id'],
            'created_by' => ['users', 'id'],
        ],
        'crm_activities' => [
            'hq_id' => ['hq_tenants', 'id'],
            'customer_id' => ['crm_customers', 'id'],
            'contact_customer_id' => ['crm_customers', 'id'],
            'opportunity_id' => ['crm_opportunities', 'id'],
            'task_id' => ['crm_tasks', 'id'],
            'assignment_event_id' => ['crm_task_assignment_events', 'id'],
            'created_by' => ['users', 'id'],
            'updated_by' => ['users', 'id'],
        ],
        'manifest_parcels' => [
            'created_by' => ['users', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
            'destination_node_id' => ['nodes', 'id'],
            'assigned_driver_id' => ['drivers', 'id'],
            'manifest_id' => ['manifests', 'id'],
            'origin_node_id' => ['nodes', 'id'],
            'parcel_id' => ['parcels', 'id'],
            'route_plan_leg_id' => ['route_plan_legs', 'id'],
            'route_plan_id' => ['route_plans', 'id'],
            'route_definition_version_id' => ['route_definition_versions', 'id'],
            'route_definition_version_leg_id' => ['route_definition_version_legs', 'id'],
            'assigned_vehicle_id' => ['vehicles', 'id'],
        ],
        'manifests' => [
            'approved_by' => ['users', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
            'assigned_driver_id' => ['drivers', 'id'],
            'assigned_vehicle_id' => ['vehicles', 'id'],
            'created_by' => ['users', 'id'],
            'destination_node_id' => ['nodes', 'id'],
            'node_id' => ['nodes', 'id'],
            'origin_node_id' => ['nodes', 'id'],
            'route_plan_id' => ['route_plans', 'id'],
            'route_plan_leg_id' => ['route_plan_legs', 'id'],
            'route_definition_version_id' => ['route_definition_versions', 'id'],
            'route_definition_version_leg_id' => ['route_definition_version_legs', 'id'],
            'source_manifest_id' => ['manifests', 'id'],
        ],
        'idempotency_records' => [
            'actor_id' => ['users', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
        ],
        'nodes' => [
            'city_id' => ['cities', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
            'area_id' => ['areas', 'id'],
            'province_id' => ['provinces', 'id'],
        ],
        'areas' => [
            'hq_id' => ['hq_tenants', 'id'],
        ],
        'area_hierarchies' => [
            'hq_id' => ['hq_tenants', 'id'],
        ],
        'audit_events' => [
            'hq_id' => ['hq_tenants', 'id'],
            'initiator_id' => ['users', 'id'],
        ],
        'user_invitations' => [
            'created_by' => ['users', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
            'user_id' => ['users', 'id'],
        ],
        'user_sessions' => [
            'hq_id' => ['hq_tenants', 'id'],
            'user_id' => ['users', 'id'],
        ],
        'authentication_credentials' => [
            'user_id' => ['users', 'id'],
        ],
        'otp_challenges' => [
            'user_id' => ['users', 'id'],
        ],
        'route_plans' => [
            'hq_id' => ['hq_tenants', 'id'],
            'consignment_id' => ['consignments', 'id'],
            'created_by' => ['users', 'id'],
            'route_definition_id' => ['route_definitions', 'id'],
            'route_definition_version_id' => ['route_definition_versions', 'id'],
        ],
        'route_plan_legs' => [
            'hq_id' => ['hq_tenants', 'id'],
            'destination_node_id' => ['nodes', 'id'],
            'origin_node_id' => ['nodes', 'id'],
            'route_plan_id' => ['route_plans', 'id'],
            'source_route_definition_version_leg_id' => ['route_definition_version_legs', 'id'],
        ],
        'route_definitions' => [
            'hq_id' => ['hq_tenants', 'id'],
            'published_version_id' => ['route_definition_versions', 'id'],
        ],
        'last_mile_resolution_evidence' => [
            'hq_id' => ['hq_tenants', 'id'],
            'consignment_id' => ['consignments', 'id'],
            'coverage_rule_id' => ['coverage_rules', 'id'],
            'coverage_policy_version_id' => ['coverage_policy_versions', 'id'],
            'destination_gateway_node_id' => ['nodes', 'id'],
            'last_mile_node_id' => ['nodes', 'id'],
            'route_plan_id' => ['route_plans', 'id'],
            'route_definition_version_id' => ['route_definition_versions', 'id'],
            'resolved_by' => ['users', 'id'],
            'coverage_policy_id' => ['coverage_policies', 'id'],
        ],
        'pickup_tasks' => [
            'hq_id' => ['hq_tenants', 'id'],
            'consignment_id' => ['consignments', 'id'],
            'assigned_driver_id' => ['drivers', 'id'],
            'node_id' => ['nodes', 'id'],
        ],
        'vehicles' => [
            'hq_id' => ['hq_tenants', 'id'],
            'home_node_id' => ['nodes', 'id'],
        ],
        'operational_exception_history' => [
            'actor_id' => ['users', 'id'],
            'exception_case_id' => ['operational_exception_cases', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
        ],
        'delivery_task_history' => [
            'actor_id' => ['users', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
            'consignment_id' => ['consignments', 'id'],
            'assigned_driver_id' => ['drivers', 'id'],
            'delivery_task_id' => ['delivery_tasks', 'id'],
        ],
        'coverage_policy_versions' => [
            'approved_by' => ['users', 'id'],
            'created_by' => ['users', 'id'],
            'published_by' => ['users', 'id'],
            'validated_by' => ['users', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
            'coverage_policy_id' => ['coverage_policies', 'id'],
        ],
        'delivery_tasks' => [
            'hq_id' => ['hq_tenants', 'id'],
            'consignment_id' => ['consignments', 'id'],
            'assigned_driver_id' => ['drivers', 'id'],
            'last_mile_resolution_id' => ['last_mile_resolution_evidence', 'id'],
            'manifest_id' => ['manifests', 'id'],
            'node_id' => ['nodes', 'id'],
        ],
        'route_plan_resolution_evidence' => [
            'hq_id' => ['hq_tenants', 'id'],
            'offering_version_id' => ['service_offering_versions', 'id'],
            'consignment_id' => ['consignments', 'id'],
            'coverage_policy_version_id' => ['coverage_policy_versions', 'id'],
            'route_definition_id' => ['route_definitions', 'id'],
            'destination_gateway_node_id' => ['nodes', 'id'],
            'route_plan_id' => ['route_plans', 'id'],
            'coverage_policy_id' => ['coverage_policies', 'id'],
            'route_definition_version_id' => ['route_definition_versions', 'id'],
            'coverage_rule_id' => ['coverage_rules', 'id'],
        ],
        'drivers' => [
            'hq_id' => ['hq_tenants', 'id'],
            'home_node_id' => ['nodes', 'id'],
            'user_id' => ['users', 'id'],
        ],
        'route_definition_version_legs' => [
            'hq_id' => ['hq_tenants', 'id'],
            'destination_node_id' => ['nodes', 'id'],
            'origin_node_id' => ['nodes', 'id'],
            'route_definition_version_id' => ['route_definition_versions', 'id'],
        ],
        'route_definition_legs' => [
            'hq_id' => ['hq_tenants', 'id'],
            'destination_node_id' => ['nodes', 'id'],
            'origin_node_id' => ['nodes', 'id'],
            'route_definition_id' => ['route_definitions', 'id'],
        ],
        'operational_exception_cases' => [
            'hq_id' => ['hq_tenants', 'id'],
            'consignment_id' => ['consignments', 'id'],
            'driver_id' => ['drivers', 'id'],
            'manifest_id' => ['manifests', 'id'],
            'reviewed_by' => ['users', 'id'],
            'submitted_by' => ['users', 'id'],
            'parcel_id' => ['parcels', 'id'],
            'pickup_task_id' => ['pickup_tasks', 'id'],
            'delivery_task_id' => ['delivery_tasks', 'id'],
        ],
        'coverage_rules' => [
            'city_id' => ['cities', 'id'],
            'offering_version_id' => ['service_offering_versions', 'id'],
            'province_id' => ['provinces', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
            'target_node_id' => ['nodes', 'id'],
            'coverage_policy_version_id' => ['coverage_policy_versions', 'id'],
        ],
        'driver_capabilities' => [
            'hq_id' => ['hq_tenants', 'id'],
            'driver_id' => ['drivers', 'id'],
        ],
        'coverage_policies' => [
            'hq_id' => ['hq_tenants', 'id'],
            'published_version_id' => ['coverage_policy_versions', 'id'],
        ],
        'route_definition_versions' => [
            'approved_by' => ['users', 'id'],
            'created_by' => ['users', 'id'],
            'offering_version_id' => ['service_offering_versions', 'id'],
            'published_by' => ['users', 'id'],
            'validated_by' => ['users', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
            'route_definition_id' => ['route_definitions', 'id'],
            'destination_node_id' => ['nodes', 'id'],
            'origin_node_id' => ['nodes', 'id'],
        ],
        'outbox_events' => [
            'hq_id' => ['hq_tenants', 'id'],
        ],
        'pricing_charge_lines' => [
            'charge_type_id' => ['pricing_charge_types', 'id'],
            'pricing_snapshot_id' => ['pricing_snapshots', 'id'],
            'rate_rule_id' => ['tariff_rate_rules', 'id'],
        ],
        'pricing_quote_lines' => [
            'charge_type_id' => ['pricing_charge_types', 'id'],
            'quote_id' => ['pricing_quotes', 'id'],
            'rate_rule_id' => ['tariff_rate_rules', 'id'],
        ],
        'pricing_zone_set_versions' => [
            'approved_by' => ['users', 'id'],
            'created_by' => ['users', 'id'],
            'previous_version_id' => ['pricing_zone_set_versions', 'id'],
            'pricing_zone_set_id' => ['pricing_zone_sets', 'id'],
            'published_by' => ['users', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
        ],
        'pricing_zones' => [
            'zone_set_version_id' => ['pricing_zone_set_versions', 'id'],
        ],
        'tariff_rate_rules' => [
            'charge_type_id' => ['pricing_charge_types', 'id'],
            'destination_zone_id' => ['pricing_zones', 'id'],
            'origin_zone_id' => ['pricing_zones', 'id'],
            'service_offering_version_id' => ['service_offering_versions', 'id'],
            'tariff_version_id' => ['tariff_versions', 'id'],
            'service_option_version_id' => ['service_option_versions', 'id'],
        ],
        'pricing_zone_sets' => [
            'created_by' => ['users', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
        ],
        'pricing_quotes' => [
            'destination_zone_id' => ['pricing_zones', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
            'origin_zone_id' => ['pricing_zones', 'id'],
            'requested_by' => ['users', 'id'],
            'service_offering_id' => ['service_offerings', 'id'],
            'service_offering_version_id' => ['service_offering_versions', 'id'],
            'tariff_version_id' => ['tariff_versions', 'id'],
            'zone_set_version_id' => ['pricing_zone_set_versions', 'id'],
        ],
        'tariff_families' => [
            'created_by' => ['users', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
            'service_charge_type_id' => ['pricing_charge_types', 'id'],
        ],
        'pricing_snapshots' => [
            'accepted_by' => ['users', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
            'quote_id' => ['pricing_quotes', 'id'],
        ],
        'tariff_service_attachments' => [
            'service_tariff_family_id' => ['tariff_families', 'id'],
            'tariff_version_id' => ['tariff_versions', 'id'],
        ],
        'tariff_versions' => [
            'approved_by' => ['users', 'id'],
            'created_by' => ['users', 'id'],
            'previous_version_id' => ['tariff_versions', 'id'],
            'published_by' => ['users', 'id'],
            'tariff_family_id' => ['tariff_families', 'id'],
            'zone_set_version_id' => ['pricing_zone_set_versions', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
        ],
        'pricing_zone_members' => [
            'city_id' => ['cities', 'id'],
            'pricing_zone_id' => ['pricing_zones', 'id'],
            'province_id' => ['provinces', 'id'],
        ],
        'commitment_schedule_windows' => [
            'commitment_schedule_version_id' => ['commitment_schedule_versions', 'id'],
        ],
        'service_offering_option_rules' => [
            'service_option_version_id' => ['service_option_versions', 'id'],
            'service_offering_version_id' => ['service_offering_versions', 'id'],
        ],
        'service_offering_commitment_bindings' => [
            'service_offering_version_id' => ['service_offering_versions', 'id'],
            'commitment_schedule_version_id' => ['commitment_schedule_versions', 'id'],
        ],
        'commitment_schedule_versions' => [
            'approved_by' => ['users', 'id'],
            'created_by' => ['users', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
            'commitment_schedule_id' => ['commitment_schedules', 'id'],
            'previous_version_id' => ['commitment_schedule_versions', 'id'],
            'published_by' => ['users', 'id'],
        ],
        'shipping_method_versions' => [
            'approved_by' => ['users', 'id'],
            'created_by' => ['users', 'id'],
            'previous_version_id' => ['shipping_method_versions', 'id'],
            'published_by' => ['users', 'id'],
            'shipping_method_id' => ['shipping_methods', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
        ],
        'commitment_schedule_scopes' => [
            'hq_id' => ['hq_tenants', 'id'],
            'node_id' => ['nodes', 'id'],
            'commitment_schedule_version_id' => ['commitment_schedule_versions', 'id'],
        ],
        'service_option_versions' => [
            'approved_by' => ['users', 'id'],
            'created_by' => ['users', 'id'],
            'previous_version_id' => ['service_option_versions', 'id'],
            'published_by' => ['users', 'id'],
            'service_option_id' => ['service_options', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
        ],
        'service_offering_versions' => [
            'approved_by' => ['users', 'id'],
            'created_by' => ['users', 'id'],
            'previous_version_id' => ['service_offering_versions', 'id'],
            'published_by' => ['users', 'id'],
            'service_offering_id' => ['service_offerings', 'id'],
            'service_type_version_id' => ['service_type_versions', 'id'],
            'shipping_method_version_id' => ['shipping_method_versions', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
        ],
        'service_offerings' => [
            'created_by' => ['users', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
        ],
        'service_eligibility_rules' => [
            'service_offering_version_id' => ['service_offering_versions', 'id'],
        ],
        'service_availability_bindings' => [
            'service_offering_version_id' => ['service_offering_versions', 'id'],
        ],
        'service_type_versions' => [
            'approved_by' => ['users', 'id'],
            'created_by' => ['users', 'id'],
            'previous_version_id' => ['service_type_versions', 'id'],
            'published_by' => ['users', 'id'],
            'service_type_id' => ['service_types', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
        ],
        'commitment_schedules' => [
            'created_by' => ['users', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
        ],
        'shipping_methods' => [
            'created_by' => ['users', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
        ],
        'service_options' => [
            'created_by' => ['users', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
        ],
        'service_coverage_references' => [
            'service_offering_version_id' => ['service_offering_versions', 'id'],
        ],
        'service_types' => [
            'created_by' => ['users', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
        ],
        'service_legacy_mappings' => [
            'hq_id' => ['hq_tenants', 'id'],
        ],
        'cities' => [
            'province_id' => ['provinces', 'id'],
        ],
        'notification_deliveries' => [
            'event_id' => ['outbox_events', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
        ],
        'operational_statuses' => [
            'hq_id' => ['hq_tenants', 'id'],
        ],
        'parcel_custody_events' => [
            'hq_id' => ['hq_tenants', 'id'],
            'consignment_id' => ['consignments', 'id'],
            'parcel_id' => ['parcels', 'id'],
            'initiator_id' => ['users', 'id'],
            'from_node_id' => ['nodes', 'id'],
            'to_node_id' => ['nodes', 'id'],
            'manifest_id' => ['manifests', 'id'],
            'route_plan_id' => ['route_plans', 'id'],
            'route_plan_leg_id' => ['route_plan_legs', 'id'],
        ],
        'consignment_status_events' => [
            'initiator_id' => ['users', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
            'consignment_id' => ['consignments', 'id'],
            'manifest_id' => ['manifests', 'id'],
            'node_id' => ['nodes', 'id'],
            'parcel_id' => ['parcels', 'id'],
            'driver_id' => ['drivers', 'id'],
        ],
        'consignments' => [
            'active_pricing_snapshot_id' => ['pricing_snapshots', 'id'],
            'commitment_schedule_version_id' => ['commitment_schedule_versions', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
            'delivery_node_id' => ['nodes', 'id'],
            'initiator_id' => ['users', 'id'],
            'pickup_node_id' => ['nodes', 'id'],
            'receiver_city_id' => ['cities', 'id'],
            'sender_city_id' => ['cities', 'id'],
            'service_offering_id' => ['service_offerings', 'id'],
            'service_offering_version_id' => ['service_offering_versions', 'id'],
            'pickup_man_id' => ['drivers', 'id'],
            'delivery_man_id' => ['drivers', 'id'],
        ],
        'parcels' => [
            'hq_id' => ['hq_tenants', 'id'],
            'active_route_plan_leg_id' => ['route_plan_legs', 'id'],
            'active_route_plan_id' => ['route_plans', 'id'],
            'consignment_id' => ['consignments', 'id'],
            'current_node_id' => ['nodes', 'id'],
        ],
        'consignment_number_ranges' => [
            'created_by' => ['users', 'id'],
            'disabled_by' => ['users', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
        ],
        'consignment_pricing_versions' => [
            'accepted_by' => ['users', 'id'],
            'pricing_snapshot_id' => ['pricing_snapshots', 'id'],
            'service_offering_version_id' => ['service_offering_versions', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
            'consignment_id' => ['consignments', 'id'],
        ],
        'consignment_pricing_charge_lines' => [
            'hq_id' => ['hq_tenants', 'id'],
            'pricing_version_id' => ['consignment_pricing_versions', 'id'],
        ],
        'consignment_number_allocations' => [
            'allocated_by' => ['users', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
            'consignment_id' => ['consignments', 'id'],
            'range_id' => ['consignment_number_ranges', 'id'],
        ],
        'users' => [
            'created_by' => ['users', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
        ],
        'user_role_assignments' => [
            'assigned_by' => ['users', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
            'revoked_by' => ['users', 'id'],
            'role_id' => ['roles', 'id'],
            'user_id' => ['users', 'id'],
        ],
        'roles' => [
            'created_by' => ['users', 'id'],
            'hq_id' => ['hq_tenants', 'id'],
        ],
        'role_menu_preferences' => [
            'role_id' => ['roles', 'id'],
        ],
        'role_menu_items' => [
            'role_id' => ['roles', 'id'],
        ],
        'tenant_module_entitlements' => [
            'hq_id' => ['hq_tenants', 'id'],
            'updated_by' => ['users', 'id'],
        ],
        'role_permissions' => [
            'created_by' => ['users', 'id'],
            'permission_id' => ['permissions', 'id'],
            'role_id' => ['roles', 'id'],
        ],
        'operational_status_revisions' => [
            'actor_id' => ['users', 'id'],
        ],
    ];

    public const POLYMORPHIC = [
        // The registry of records a document may be attached to; the owning enum is
        // Modules\DocumentStore\Domain\Enums\DocumentResourceType and the two are kept in step.
        'document_links' => [
            'resource_id' => ['resource_type', [
                'CUSTOMER' => ['crm_customers', 'id'],
                'OPPORTUNITY' => ['crm_opportunities', 'id'],
            ]],
        ],
        'user_role_assignments' => [
            'scope_id' => ['scope_type', [
                'TENANT' => ['hq_tenants', 'id'],
                'AREA' => ['areas', 'id'],
                'NODE' => ['nodes', 'id'],
                'SELF' => ['users', 'id'],
            ]],
        ],
        'parcels' => [
            'current_custodian_id' => ['current_custody_type', [
                'NODE' => ['nodes', 'id'],
                'PICKUP_DRIVER' => ['drivers', 'id'],
                'LINEHAUL_DRIVER' => ['drivers', 'id'],
                'DELIVERY_DRIVER' => ['drivers', 'id'],
            ]],
        ],
        'parcel_custody_events' => [
            'from_custodian_id' => ['from_custody_type', [
                'NODE' => ['nodes', 'id'],
                'PICKUP_DRIVER' => ['drivers', 'id'],
                'LINEHAUL_DRIVER' => ['drivers', 'id'],
                'DELIVERY_DRIVER' => ['drivers', 'id'],
            ]],
            'to_custodian_id' => ['to_custody_type', [
                'NODE' => ['nodes', 'id'],
                'PICKUP_DRIVER' => ['drivers', 'id'],
                'LINEHAUL_DRIVER' => ['drivers', 'id'],
                'DELIVERY_DRIVER' => ['drivers', 'id'],
            ]],
        ],
    ];

    /** @return array{string, string}|null */
    public static function reference(string $table, string $column, array $attributes = []): ?array
    {
        if (isset(self::REFERENCES[$table][$column])) {
            return self::REFERENCES[$table][$column];
        }
        if (isset(self::POLYMORPHIC[$table][$column])) {
            [$type, $targets] = self::POLYMORPHIC[$table][$column];

            return $targets[$attributes[$type] ?? ''] ?? null;
        }
        if ($column === 'owner_key' && in_array($table, ['roles', 'operational_statuses'], true)) {
            return ['hq_tenants', 'id'];
        }

        return null;
    }

    /** @return list<string> */
    public static function columns(string $table): array
    {
        $columns = array_merge(array_keys(self::REFERENCES[$table] ?? []), array_keys(self::POLYMORPHIC[$table] ?? []));
        if (in_array($table, ['roles', 'operational_statuses'], true)) {
            $columns[] = 'owner_key';
        }

        return $columns;
    }
}
