<?php

declare(strict_types=1);

namespace Modules\Pricing\Domain\Enums;

enum MatrixValidationCode: string
{
    case MATRIX_ID_DUPLICATE = 'PRICING_MATRIX_ID_DUPLICATE';
    case MATRIX_CONTEXT_DUPLICATE = 'PRICING_MATRIX_CONTEXT_DUPLICATE';
    case MATRIX_POLICY_MISMATCH = 'PRICING_MATRIX_POLICY_MISMATCH';
    case MATRIX_ZONES_INVALID = 'PRICING_MATRIX_ZONES_INVALID';
    case MATRIX_EMPTY = 'PRICING_MATRIX_EMPTY';
    case LINEAR_TAIL_INVALID = 'PRICING_LINEAR_TAIL_INVALID';
    case LINEAR_BASE_REQUIRED = 'PRICING_LINEAR_BASE_REQUIRED';
    case RANGE_INVALID = 'PRICING_RANGE_INVALID';
    case RULE_RANGE_OVERLAP = 'PRICING_RULE_RANGE_OVERLAP';
    case MATRIX_RANGE_GAP = 'PRICING_MATRIX_RANGE_GAP';
    case MATRIX_STATE_INVALID = 'PRICING_MATRIX_STATE_INVALID';
    case BASE_RATE_INVALID = 'PRICING_BASE_RATE_INVALID';
    case MATRIX_RATE_MISSING = 'PRICING_MATRIX_RATE_MISSING';
}
