<?php

declare(strict_types=1);

namespace Modules\Pricing\Domain\Enums;

enum PricingValidationCode: string
{
    case ZONE_POLICY_INVALID = 'PRICING_ZONE_POLICY_INVALID';
    case RANK_REQUIRES_MATRIX = 'PRICING_RANK_REQUIRES_MATRIX';
    case MATRIX_RULE_CONFLICT = 'PRICING_MATRIX_RULE_CONFLICT';
    case SERVICE_COMPOSITION_INVALID = 'PRICING_SERVICE_COMPOSITION_INVALID';
    case ZONE_RANK_INCOMPLETE = 'PRICING_ZONE_RANK_INCOMPLETE';
    case ZONE_VERSION_NOT_PUBLISHED = 'PRICING_ZONE_VERSION_NOT_PUBLISHED';
    case VALID_FROM_REQUIRED = 'PRICING_VALID_FROM_REQUIRED';
    case EFFECTIVE_INTERVAL_INVALID = 'PRICING_EFFECTIVE_INTERVAL_INVALID';
    case EFFECTIVE_INTERVAL_OVERLAP = 'PRICING_EFFECTIVE_INTERVAL_OVERLAP';
    case RULE_NOT_FOUND = 'PRICING_RULE_NOT_FOUND';
    case SERVICE_VERSION_NOT_PUBLISHED = 'PRICING_SERVICE_VERSION_NOT_PUBLISHED';
    case SERVICE_OPTION_NOT_BOUND = 'PRICING_SERVICE_OPTION_NOT_BOUND';
    case RANGE_INVALID = 'PRICING_RANGE_INVALID';
    case FIXED_AMOUNT_REQUIRED = 'PRICING_FIXED_AMOUNT_REQUIRED';
    case UNIT_RATE_REQUIRED = 'PRICING_UNIT_RATE_REQUIRED';
    case SLAB_RATE_REQUIRED = 'PRICING_SLAB_RATE_REQUIRED';
    case PERCENTAGE_REQUIRED = 'PRICING_PERCENTAGE_REQUIRED';
    case MIN_MAX_BOUND_REQUIRED = 'PRICING_MIN_MAX_BOUND_REQUIRED';
    case MIN_MAX_INVALID = 'PRICING_MIN_MAX_INVALID';
    case AMOUNT_ROUNDING_STEP_REQUIRED = 'PRICING_AMOUNT_ROUNDING_STEP_REQUIRED';
    case RULE_AMBIGUOUS = 'PRICING_RULE_AMBIGUOUS';
    case RULE_RANGE_OVERLAP = 'PRICING_RULE_RANGE_OVERLAP';
    case SERVICE_DEPENDENCY_INVALID = 'PRICING_SERVICE_DEPENDENCY_INVALID';
    case DEFAULT_CONFLICT = 'PRICING_DEFAULT_CONFLICT';
    case POLYGON_INVALID_OR_OVERLAPPING = 'PRICING_POLYGON_INVALID_OR_OVERLAPPING';
    case ZONE_REQUIRED = 'PRICING_ZONE_REQUIRED';
    case ZONE_AMBIGUOUS = 'PRICING_ZONE_AMBIGUOUS';
}
