<?php

declare(strict_types=1);

namespace Tests\Feature;

use Illuminate\Routing\Route;
use Tests\TestCase;

final class ModuleRouteRegistrationTest extends TestCase
{
    public function test_s0_04_registers_the_complete_approved_operation_set(): void
    {
        $routes = collect(app('router')->getRoutes()->getRoutes())
            ->filter(fn (Route $route): bool => str_starts_with($route->uri(), 'api/v1/'))
            ->map(fn (Route $route): string => $route->methods()[0].' /'.$route->uri())
            ->sort()
            ->values()
            ->all();

        $expected = [
            'GET /api/v1/admin/consignment-number-ranges',
            'GET /api/v1/admin/consignment-number-ranges/{rangeId}',
            'GET /api/v1/admin/consignment-number-ranges/{rangeId}/allocations',
            'GET /api/v1/admin/pricing/service-tariffs/references',
            'GET /api/v1/admin/service-catalog/commitment-zone-groups',
            'GET /api/v1/admin/service-catalog/records/{resource}/{identityId}',
            'GET /api/v1/operational-statuses',
            'PATCH /api/v1/admin/service-catalog/records/{resource}/{identityId}/status',
            'PATCH /api/v1/operational-statuses/{id}',
            'POST /api/v1/admin/consignment-number-ranges',
            'POST /api/v1/admin/consignment-number-ranges/validate',
            'POST /api/v1/admin/consignment-number-ranges/{rangeId}/disable',
            'POST /api/v1/admin/pricing/matrix-workbooks/preview',
            'POST /api/v1/admin/pricing/matrix-workbooks/sample',
            'POST /api/v1/admin/pricing/tariff-versions/{versionId}/simulate',
            'POST /api/v1/admin/service-catalog/records/{resource}',
            'POST /api/v1/operational-statuses',
            'PUT /api/v1/admin/service-catalog/records/{resource}/{identityId}',

            'DELETE /api/v1/iam/users/{userId}/role-assignments/{assignmentId}',
            'DELETE /api/v1/me/sessions/{sessionId}',
            'GET /api/v1/admin/pricing/audit',
            'GET /api/v1/admin/pricing/charge-types',
            'GET /api/v1/admin/pricing/tariff-families',
            'GET /api/v1/admin/pricing/zone-set-versions/references',
            'GET /api/v1/admin/pricing/zone-sets',
            'GET /api/v1/admin/pricing/{kind}/identities/{identityId}/versions',
            'GET /api/v1/admin/service-catalog/audit',
            'GET /api/v1/admin/service-catalog/commitment-schedules',
            'GET /api/v1/admin/service-catalog/commitment-schedules/identities/{identityId}/versions',
            'GET /api/v1/admin/service-catalog/commitment-schedules/published-versions',
            'GET /api/v1/admin/service-catalog/{resource}',
            'GET /api/v1/admin/service-catalog/{resource}/identities/{identityId}/versions',
            'GET /api/v1/admin/service-catalog/{resource}/published-versions',
            'GET /api/v1/context/nodes',
            'GET /api/v1/crm/customers/{customerId}/addresses',
            'POST /api/v1/crm/customers/{customerId}/addresses',
            'GET /api/v1/crm/customers/{customerId}/addresses/{addressId}',
            'PATCH /api/v1/crm/customers/{customerId}/addresses/{addressId}',
            'GET /api/v1/crm/customers/{customerId}/bank-accounts',
            'POST /api/v1/crm/customers/{customerId}/bank-accounts',
            'GET /api/v1/crm/customers/{customerId}/detail',
            'GET /api/v1/tasks',
            'POST /api/v1/tasks',
            'POST /api/v1/tasks/{taskId}/complete',
            'POST /api/v1/tasks/{taskId}/assignments',
            'POST /api/v1/tasks/{taskId}/actions',
            'GET /api/v1/crm/customers/{customerId}/extended-details',
            'PUT /api/v1/crm/customers/{customerId}/extended-details',
            'GET /api/v1/crm/customers/{customerId}/external-invoices',
            'POST /api/v1/crm/customers/{customerId}/external-invoices',
            'GET /api/v1/crm/customers/{customerId}/financial-details',
            'PUT /api/v1/crm/customers/{customerId}/financial-details',
            'GET /api/v1/crm/customers/{customerId}/financial-entries',
            'GET /api/v1/crm/customers/{customerId}/history',
            'GET /api/v1/crm/customers/{customerId}/history/timeline',
            'GET /api/v1/crm/customers/{customerId}/history/{category}',
            'POST /api/v1/crm/customers/{customerId}/financial-entries',
            'POST /api/v1/crm/financial-entries/{entryId}/allocations',
            'GET /api/v1/crm/document-categories',
            'GET /api/v1/crm/documents',
            'POST /api/v1/crm/documents',
            'PATCH /api/v1/crm/documents/{documentId}',
            'POST /api/v1/crm/documents/{documentId}/archive',
            'POST /api/v1/crm/documents/{documentId}/links',
            'GET /api/v1/crm/sales-documents',
            'POST /api/v1/crm/sales-documents',
            'GET /api/v1/crm/sales-documents/{documentId}',
            'POST /api/v1/crm/sales-documents/{documentId}/versions',
            'POST /api/v1/crm/sales-document-versions/{versionId}/accept',
            'POST /api/v1/crm/sales-document-versions/{versionId}/cancel',
            'POST /api/v1/crm/sales-document-versions/{versionId}/issue',
            'GET /api/v1/crm/sales-funnels',
            'GET /api/v1/crm/opportunities',
            'POST /api/v1/crm/opportunities',
            'POST /api/v1/crm/opportunities/{opportunityId}/step-transitions',
            'GET /api/v1/crm/opportunities/{opportunityId}/events',
            'GET /api/v1/crm/customers/{customerId}/profile',
            'GET /api/v1/crm/customers/{customerId}/org-structure',
            'POST /api/v1/crm/customers/{customerId}/departments',
            'PATCH /api/v1/crm/customers/{customerId}/departments/{departmentId}',
            'POST /api/v1/crm/customers/{customerId}/departments/{departmentId}/positions',
            'PATCH /api/v1/crm/customers/{customerId}/positions/{positionId}',
            'PATCH /api/v1/crm/customers/{customerId}/profile',
            'GET /api/v1/crm/industries',
            'GET /api/v1/crm/teams',
            'GET /api/v1/crm/team-members',
            'POST /api/v1/crm/teams',
            'PATCH /api/v1/crm/teams/{teamId}',
            'POST /api/v1/crm/teams/{teamId}/members',
            'POST /api/v1/crm/memberships/{membershipId}/end',
            'POST /api/v1/crm/memberships/bulk',
            'POST /api/v1/crm/memberships/bulk/preview',
            'GET /api/v1/customers',
            'GET /api/v1/consignments',
            'GET /api/v1/consignments/{consignmentId}',
            'GET /api/v1/dashboard/operations',
            'GET /api/v1/delivery-tasks',
            'GET /api/v1/delivery-tasks/{id}',
            'GET /api/v1/drivers',
            'GET /api/v1/manifests',
            'GET /api/v1/manifests/context-options',
            'GET /api/v1/manifests/{manifestId}',
            'GET /api/v1/manifests/{manifestId}/exception',
            'GET /api/v1/manifests/{manifestId}/eligible-parcels',
            'GET /api/v1/iam/module-entitlements',
            'GET /api/v1/iam/permissions',
            'GET /api/v1/iam/assignment-options',
            'GET /api/v1/iam/roles',
            'GET /api/v1/iam/roles/{roleId}',
            'GET /api/v1/iam/users',
            'GET /api/v1/iam/users/{userId}',
            'GET /api/v1/me',
            'GET /api/v1/me/context',
            'GET /api/v1/me/sessions',
            'GET /api/v1/network/areas',
            'GET /api/v1/network/areas/{areaId}',
            'GET /api/v1/network/coverage-policies',
            'GET /api/v1/network/coverage-policies/{policyId}',
            'GET /api/v1/network/coverage-policies/{policyId}/versions',
            'GET /api/v1/network/coverage-policies/{policyId}/versions/{versionId}',
            'GET /api/v1/network/nodes',
            'GET /api/v1/network/nodes/{nodeId}',
            'GET /api/v1/network/route-definitions',
            'GET /api/v1/network/route-definitions/{definitionId}',
            'GET /api/v1/network/route-definitions/{definitionId}/versions',
            'GET /api/v1/network/route-definitions/{definitionId}/versions/{versionId}',
            'GET /api/v1/fleet/drivers',
            'GET /api/v1/fleet/drivers/{driver_id}',
            'GET /api/v1/fleet/vehicles',
            'GET /api/v1/fleet/vehicles/{vehicle_id}',
            'GET /api/v1/pickup-tasks',
            'GET /api/v1/pickup-tasks/{id}',
            'GET /api/v1/pricing/quotes/{quoteId}',
            'GET /api/v1/reference/cities',
            'GET /api/v1/reference/cities/{cityId}',
            'GET /api/v1/reference/countries',
            'GET /api/v1/reference/countries/{countryId}',
            'GET /api/v1/reference/provinces',
            'GET /api/v1/route-definitions',
            'GET /api/v1/route-plans',
            'GET /api/v1/route-plans/{id}',
            'GET /api/v1/services/pickup-windows',
            'GET /api/v1/vehicles',
            'PATCH /api/v1/admin/pricing/tariff-versions/{versionId}',
            'PATCH /api/v1/admin/pricing/zone-set-versions/{versionId}',
            'PATCH /api/v1/admin/service-catalog/commitment-schedules/versions/{versionId}',
            'PATCH /api/v1/admin/service-catalog/{resource}/versions/{versionId}',
            'PATCH /api/v1/iam/roles/{roleId}',
            'PATCH /api/v1/consignments/{consignmentId}',
            'PATCH /api/v1/iam/users/{userId}',
            'PATCH /api/v1/iam/users/{userId}/role-assignments/{assignmentId}',
            'PATCH /api/v1/manifests/{manifestId}',
            'PATCH /api/v1/me/profile',
            'PATCH /api/v1/network/areas/{areaId}',
            'PATCH /api/v1/network/coverage-policies/{policyId}/versions/{versionId}',
            'PATCH /api/v1/network/nodes/{nodeId}',
            'PATCH /api/v1/network/route-definitions/{definitionId}/versions/{versionId}',
            'PATCH /api/v1/fleet/drivers/{driver_id}',
            'PATCH /api/v1/fleet/vehicles/{vehicle_id}',
            'POST /api/v1/admin/pricing/charge-types',
            'POST /api/v1/admin/pricing/tariff-families',
            'POST /api/v1/admin/pricing/tariff-versions/{versionId}/validate',
            'POST /api/v1/admin/pricing/zone-set-versions/{versionId}/validate',
            'POST /api/v1/admin/pricing/zone-sets',
            'POST /api/v1/admin/pricing/{kind}/identities/{identityId}/versions',
            'POST /api/v1/admin/pricing/{kind}/{versionId}/{action}',
            'POST /api/v1/admin/service-catalog/{resource}',
            'POST /api/v1/admin/service-catalog/commitment-schedules',
            'POST /api/v1/admin/service-catalog/commitment-schedules/identities/{identityId}/versions',
            'POST /api/v1/admin/service-catalog/commitment-schedules/versions/{versionId}/validate',
            'POST /api/v1/admin/service-catalog/commitment-schedules/versions/{versionId}/{action}',
            'POST /api/v1/admin/service-catalog/{resource}/identities/{identityId}/versions',
            'POST /api/v1/admin/service-catalog/{resource}/versions/{versionId}/validate',
            'POST /api/v1/admin/service-catalog/{resource}/versions/{versionId}/{action}',
            'POST /api/v1/auth/login',
            'POST /api/v1/auth/logout',
            'POST /api/v1/auth/logout-all',
            'POST /api/v1/auth/otp/send',
            'POST /api/v1/auth/otp/verify',
            'POST /api/v1/auth/password/activate',
            'POST /api/v1/auth/password/change',
            'POST /api/v1/auth/password/reset',
            'POST /api/v1/auth/refresh',
            'POST /api/v1/consignments',
            'POST /api/v1/consignments/pricing-quotes',
            'POST /api/v1/consignments/{consignmentId}/cluster',
            'POST /api/v1/consignments/{consignmentId}/route-plan',
            'POST /api/v1/delivery-tasks/{id}/assign',
            'POST /api/v1/delivery-tasks/{id}/complete',
            'POST /api/v1/delivery-tasks/{id}/fail',
            'POST /api/v1/delivery-tasks/{id}/retry',
            'POST /api/v1/iam/roles',
            'POST /api/v1/iam/roles/{roleId}/clone',
            'POST /api/v1/iam/users',
            'POST /api/v1/iam/users/{userId}/operational-profile',
            'POST /api/v1/iam/users/{userId}/activate',
            'POST /api/v1/iam/users/{userId}/deactivate',
            'POST /api/v1/iam/users/{userId}/invite',
            'POST /api/v1/iam/users/{userId}/revoke-sessions',
            'POST /api/v1/iam/users/{userId}/role-assignments',
            'POST /api/v1/iam/users/{userId}/suspend',
            'POST /api/v1/iam/users/{userId}/temporary-password',
            'POST /api/v1/network/areas',
            'POST /api/v1/network/coverage-policies',
            'POST /api/v1/network/coverage-policies/{policyId}/versions',
            'POST /api/v1/network/coverage-policies/{policyId}/versions/{versionId}/{action}',
            'POST /api/v1/network/nodes',
            'POST /api/v1/network/route-definitions',
            'POST /api/v1/network/route-definitions/{definitionId}/versions',
            'POST /api/v1/network/route-definitions/{definitionId}/versions/{versionId}/{action}',
            'POST /api/v1/fleet/drivers',
            'POST /api/v1/fleet/vehicles',
            'POST /api/v1/manifests',
            'POST /api/v1/manifests/{manifestId}/confirm',
            'POST /api/v1/manifests/{manifestId}/exception/approve',
            'POST /api/v1/manifests/{manifestId}/exception/reject',
            'POST /api/v1/manifests/{manifestId}/exception/resubmit',
            'POST /api/v1/manifests/{manifestId}/parcels',
            'POST /api/v1/manifests/{manifestId}/validate',
            'POST /api/v1/pickup-tasks',
            'POST /api/v1/pickup-tasks/{id}/assign',
            'POST /api/v1/pickup-tasks/{id}/complete',
            'POST /api/v1/pickup-tasks/{id}/fail',
            'POST /api/v1/pricing/quotes',
            'POST /api/v1/pricing/quotes/{quoteId}/reject',
            'POST /api/v1/pricing/snapshots/accept',
            'POST /api/v1/customers',
            'POST /api/v1/services/resolve',
            'POST /api/v1/services/{offeringId}/commitments',
            'POST /api/v1/services/{offeringId}/validate',
            'PUT /api/v1/iam/roles/{roleId}/permissions',
        ];
        sort($expected);
        $this->assertSame($expected, $routes);
    }

    public function test_wave2_routes_are_registered_once_with_retry_sensitive_middleware(): void
    {
        $routes = collect(app('router')->getRoutes()->getRoutes());
        $wave2Names = [
            'route-plans.index',
            'manifests.context-options.index',
            'manifests.exception.show',
            'delivery-tasks.retry',
        ];

        foreach ($wave2Names as $name) {
            $this->assertCount(1, $routes->filter(fn (Route $route): bool => $route->getName() === $name), "Route {$name} must be registered exactly once.");
        }

        $middlewareByRoute = [
            'manifests.parcels.store' => 'idempotent:manifests.add-parcels',
            'manifests.validate' => 'idempotent:manifests.validate',
            'delivery-tasks.retry' => 'idempotent:delivery-tasks.retry',
        ];
        foreach ($middlewareByRoute as $name => $middleware) {
            $route = $routes->first(fn (Route $route): bool => $route->getName() === $name);
            $this->assertInstanceOf(Route::class, $route);
            $this->assertContains($middleware, $route->middleware());
        }
    }
}
