[global]
error_log = /proc/self/fd/2
daemonize = no

[www]
user = www-data
group = www-data
listen = 9000
pm = ondemand
pm.max_children = ${PHP_FPM_MAX_CHILDREN}
pm.process_idle_timeout = 10s
pm.max_requests = ${PHP_FPM_MAX_REQUESTS}
clear_env = no
catch_workers_output = yes
decorate_workers_output = no
ping.path = /fpm-ping
ping.response = pong
request_slowlog_timeout = 3s
slowlog = /proc/self/fd/2
request_terminate_timeout = 60s
security.limit_extensions = .php
